### ISSUE TITLE
Graphics

### ISSUE THREAD

**Issue by neynah** [sandforms/sandforms#17]
Not really an issue but let me know if you'd like some assistance with graphics. :)

**Comment by jacksingleton** [comment]
Woah thanks for reaching out to us, that would be awesome!

Would you want anything from us to kick off the process?

One thing we're working on right now is a written vision statement - how about when it's done (should be this week) I'll send it over to you, that way you can see if it makes sense to incorporate any of our specific goals into the logo.

Jack

**Comment by neynah** [comment]
Sure! That sounds great. Any screenshots would also be helpful. :)

**Comment by jacksingleton** [comment]
You can actually check out our continuous integration deployment here: http://sandforms-ci.meteor.com/

Keep in mind that 1) everything, but especially the look and feel is very subject to change right now (one of our tasks for this week is actually to clean up the UI) and 2) we don't currently have automated deployment to Sandstorm, so this is running outside of the Sandstorm shell

**Comment by neynah** [comment]
How's the mission statement coming along? If you don't have that, some mood/descriptor words would be helpful and I can get started on some ideas. (Hopefully in time for the meetup next week). :D

**Comment by jacksingleton** [comment]
We got something together yesterday! It's in the readme, and any changes or additions will get updated there, but for now this is what we have:

> We have two major motivations:
> 
> First, we want to reduce our society's reliance on propriatery software by creating user friendly alternatives to centralized services that monetize personal information.
> 
> Second, we want to improve the safety of those who work to protect individuals’ liberties online by providing software that actively protects their privacy.
> 
> To those ends, we are creating SandForms - a free software forms application that matches or exceeds the level of usability we have become accustomed to online while explicitly protecting the personal information of its users.

**Comment by neynah** [comment]
Thanks! What do you think about these?

![sandforms-1](https://cloud.githubusercontent.com/assets/855341/10177447/1d37eadc-66af-11e5-9267-45cf761bf0f5.png)

![sandforms-2](https://cloud.githubusercontent.com/assets/855341/10177452/214a6d8e-66af-11e5-8ee5-61b5744deef5.png)

If you like either of them or have more suggestions, I can get the icons done today.

**Comment by tamarabartlett** [comment]
Those look great! The first one is more artistic, but I think the 2nd one conveys better what the app is. Glad you're getting involved!

**Comment by jacksingleton** [comment]
Yeah I agree, the second one looks great!

**Comment by yakiradixon** [comment]
This is nice work, Néna. I prefer the first logo over the second one because the logo fits in with Sandstorm's existing themes and imagery, and our app will live within the Sandstorm environment . 

The second logo makes me think of a rack server instead of a form (I also thought about the Serverfault logo when I saw it).

**Comment by rosatolen** [comment]
I prefer the first one. In the marketplace, I don't generally pick apps from the logo alone. There's help text underneath the name to explain what it does. The color scheme is really cooool :DDD

Thanks for your help Néna. I also liked your talk at the last sandstorm meetup. I was the weird person in the back laughing too loudly.

**Comment by neynah** [comment]
It looks like the votes are even so far. Let me know if there's anything I can do to make either logo better to tilt the results. :D

@rosatolen I appreciated your laughter! Nice to know someone was enjoying my talk!

**Comment by jacksingleton** [comment]
Thanks again for the awesome icons Néna! They're merged in now, so you should be seeing them in action before the end of the month!
