### ISSUE TITLE
Do y'all want to give a lightning talk at the Sandstorm meetup tomorrow?

### ISSUE THREAD

**Issue by paulproteus** [sandforms/sandforms#30]
(Filing a GitHub issue is the only way I know to reach all of you, rather than just the ones I personally know.)

I'd love to see a demo of Sandforms at http://www.meetup.com/Sandstorm-SF-Bay-Area/events/226062960/ if anyone's willing to give one!

**Comment by jacksingleton** [comment]
We'd like to give a launch announcement!

**Comment by paulproteus** [comment]
Great! I'd be honored if you'd leave a comment on the meetup.com page!

**Comment by paulproteus** [comment]
I'd also love to see some new faces in the Sandforms world giving the talk, if any non-Jack people are interested! I see plenty of him already at things.

And if it's Jack talking, that's A-OK too. But thought I'd make sure to ask. There's a huge number of people who've worked on sandforms, as evidenced by this link:

https://github.com/sandforms/sandforms/graphs/contributors

and elsewhere, like `git log` and the GitHub pull requests I've seen on the project.

You may not think your # of people is huge, but the median number for an open source project is 1 contributor!

**Comment by paulproteus** [comment]
I should say -- new faces to _me_, in the Sandforms world.
