### ISSUE TITLE
Hitting "enter" unexpectedly submits form

### ISSUE THREAD

**Issue by timmc** [sandforms/sandforms#40]
I would expect it to move me to the next response field, not submit the form irrevocably.

**Comment by jacksingleton** [comment]
@mchaffee1 just fixed this yesterday :) Will be in the next release.

**Comment by valerie-roske** [comment]
@jacksingleton Actually, it is a really well-established pattern across the web that "enter" submits a form and you "tab" to next field. I would be hesitant to go against that convention...

**Comment by jacksingleton** [comment]
I think this would be a good thing to drive out with user feedback. @valerie-roske can we chat on Thursday? I'm in Chicago until then

**Comment by ocdtrekkie** [comment]
Welcome to the land of the cold and the miserable, Jack. :P Enjoy your stay.

**Comment by ocdtrekkie** [comment]
FWIW: On a long form, hitting Enter submitting would be surprising to me, particularly if I wasn't asked to confirm submission.

**Comment by jacksingleton** [comment]
This is fixed in 0.2.0, now available in the app store
