### ISSUE TITLE
Sandforms not rendering properly

### ISSUE THREAD

**Issue by zeigerpuppy** [sandforms/sandforms#42]
when I start Sandforms, it looks to be loading but the application does not render properly
![2016-02-24 08 45 38 pm](https://cloud.githubusercontent.com/assets/415981/13281378/99a23daa-db37-11e5-8b4f-4f65fdffe3ae.png)

It keeps reloading without ever showing the proper splash screen
I am running  an up to date Sandstorm install on Debian, behind an Apache2 reverse proxy.

Interestingly, something similar is happening with the Quick Survey App, 
all other applications are working fine.

**Comment by yakiradixon** [comment]
Wow, this is a problem. Thanks for letting us know. 
Does this grain's debug log have any interesting messages?

**Comment by jacksingleton** [comment]
Hmm, could you try Wekan and Rocket.Chat and let us know if they do the same thing?

I'm suspecting an issue I have ran into before when websockets were not properly forwarded through a proxy I was using: https://github.com/sandstorm-io/sandstorm/issues/1186

Have you configured your apache2 proxy with mod_proxy_wstunnel? (https://httpd.apache.org/docs/current/mod/mod_proxy_wstunnel.html)

**Comment by paulproteus** [comment]
Another note here:

`ProxyPass / http://whatever.whatever:whatever`

is a good start. Try adding a line to that, so you get _two_ lines:

```
ProxyPass / http://whatever.whatever:whatever/
ProxyPass / ws://whatever.whatever:whatever/
```

It _seems_ from my research that specifying the ProxyPass _twice_ and specifying _ws://_ in the second repetition should allow WebSockets to reach Sandstorm, which should also un-break SandForms. I'm not totally sure, though, so please test it and let us all know!

**Comment by zeigerpuppy** [comment]
Thanks for the suggestions, it was definitely a websockets issue.  
@paulproteus, unfortunately your snippet for apache doesn't work, I think that passing unencrypted websockets through apache is a bit bug prone.

Nevertheless, I switched to a different proxy server (nginx) and have had no problems, sandstorm is awesome!
