### ISSUE TITLE
Delete a record row

### ISSUE THREAD

**Issue by urakagi** [sandforms/sandforms#54]
Hello, we're trying to find a Sandstorm form app instead of Google Form, and Sandforms can satisfy our request.
But I'm wondering why there is not a very simple feature to delete a record row? Currently if someone inputs wrong data, the wrong row will stay forever.
Or is there a way to delete a record row only I don't know? It's quite weird there's no such feature.

Thanks!

**Comment by jacksingleton** [comment]
fixed in master by https://github.com/sandforms/sandforms/commit/b99fec78a2adfbd4fa396234ef7caff5e6171774
